### ISSUE TITLE
No component type designation for D1

### ISSUE THREAD

**Issue by hanshuebner** [c0pperdragon/SIO2SD#1]
Thanks for making your SIO2SD available.  I built it and it looks gorgeous!

I have tried an 1N4148 for D1 as there is no type designation for it in the BOM, and the board does not react to commands on the SIO bus.  Does this diode need to be a Schottky diode?  If so, can you let me know what kind of diode works best?

Thanks!  Hans

**Comment by c0pperdragon** [comment]
Yes, it needs to be a schottky diode with a forward voltage as low as possible. You may even shorten this connection when using the SIO2SD as the only device on the SIO bus (for test purposes). With multiple devices the diode is mandatory.

**Comment by hanshuebner** [comment]
Thanks!  I'll try to find a suitable type, but if you could recommend one, it'd be greatly appreciated!  Cheers!
